### PR TITLE
Fixes incorrect handling of tooltip text for scatter plots

### PR DESCRIPTION
**Pull request by zygmuntszpak**
Addresses https://github.com/GenieFramework/StipplePlotly.jl/issues/52

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
@zygmuntszpak thanks a lot for the fix. I'll review it and if everything looks good we can merge it 👍

**Comment by AbhimanyuAryan** [comment]
can you provide a scatter plot js example of this? Like these: https://plotly.com/javascript/line-and-scatter/
So I can understand this new field `text`

**Comment by zygmuntszpak** [comment]
The following code:
```julia
using StipplePlotly
using DataFrames
function create_example_dataframe()
    xs = [1.0, 2.0, 3.0, 4.0, 5.0, 1.5, 2.5, 3.5, 4.5, 5.5]    
    ys = [1.0, 6.0, 3.0, 6.0, 1.0, 4.0, 1.0, 7.0, 1.0, 4.0]
    groups = ["Team A", "Team A", "Team A", "Team A", "Team A", "Team B", "Team B", "Team B", "Team B", "Team B"]
    text = ["A-1", "A-2", "A-3", "A-4", "A-5","B-a", "B-b", "B-c", "B-d", "B-e"]
    return DataFrame(X = xs, Y = ys, Group = groups, Text = text)
end

df = create_example_dataframe()
pd = plotdata(df, :X, :Y; groupfeature = :Group, text = df.Text)
```

produces the following output

```julia
2-element Vector{PlotData}:
 scatter:
plot = scatter
mode = markers
name = Team A
text = ["A-1", "A-2", "A-3", "A-4", "A-5"]
x = [1.0, 2.0, 3.0, 4.0, 5.0]
y = [1.0, 6.0, 3.0, 6.0, 1.0]

 scatter:
plot = scatter
mode = markers
name = Team B
text = ["B-a", "B-b", "B-c", "B-d", "B-e"]
x = [1.5, 2.5, 3.5, 4.5, 5.5]
y = [4.0, 1.0, 7.0, 1.0, 4.0]
```

which corresponds to the  [Data Labels Hover](https://plotly.com/javascript/line-and-scatter/) scatter plotjs example :

```julia
var trace1 = {
  x: [1, 2, 3, 4, 5],
  y: [1, 6, 3, 6, 1],
  mode: 'markers',
  type: 'scatter',
  name: 'Team A',
  text: ['A-1', 'A-2', 'A-3', 'A-4', 'A-5'],
  marker: { size: 12 }
};

var trace2 = {
  x: [1.5, 2.5, 3.5, 4.5, 5.5],
  y: [4, 1, 7, 1, 4],
  mode: 'markers',
  type: 'scatter',
  name: 'Team B',
  text: ['B-a', 'B-b', 'B-c', 'B-d', 'B-e'],
  marker: { size: 12 }
};

var data = [ trace1, trace2 ];

var layout = {
  xaxis: {
    range: [ 0.75, 5.25 ]
  },
  yaxis: {
    range: [0, 8]
  },
  title:'Data Labels Hover'
};

Plotly.newPlot('myDiv', data, layout);
```

**Comment by zygmuntszpak** [comment]
I should point out that the `text` keyword argument was always implicitly there (it was absorbed in the `kwargs`) on line 609 in Charts.js
```julia
function plotdata(data::DataFrames.DataFrame, xfeature::Symbol, yfeature::Symbol; groupfeature::Symbol,
                  mode = "markers", plottype = StipplePlotly.Charts.PLOT_TYPE_SCATTER, kwargs...) :: Vector{PlotData}
```

It is defined as a field of PlotData on line 522
```julia
 text::Union{Vector{String},String,Nothing} = nothing
```

**Comment by AbhimanyuAryan** [comment]
@zygmuntszpak [update] I am testing this PR. If everything works I'll merge it EOD otherwise post feedback. Sorry for delay

**Comment by AbhimanyuAryan** [comment]
ok this looks good. Need to run few more tests and I'll merge 

Screenshot 2022-12-13 at 2 31 20 AM
e tests

**Pull request merged**
